import { satangFromMillion } from "./format";

export const ITF_PIN = { lat: "13.7260", lng: "100.5340", label: "ITF Tower สีลม" };

export type HuntSeed = {
  id: string;
  name: string;
  developer: string;
  zone: string;
  houseType: "detached" | "twin" | "mixed";
  hasDetached: boolean;
  hasTwin: boolean;
  million: number;
  millionMax?: number;
  priceNote: string;
  landNote: string;
  landWahTenths: number | null;
  usableSqmMin: number | null;
  usableSqmMax: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  parking: number | null;
  fitScore: number;
  valueScore: number;
  rank: number;
  commuteNote: string;
  sizeNote: string;
  caveat: string;
  lat: string;
  lng: string;
  traffic: "green" | "yellow" | "orange" | "red";
  hospitalNote: string;
  mallNote: string;
  highwayNote: string;
  schoolNote: string;
  pros: string;
  cons: string;
  budgetUnder6: boolean;
  unitCheck: boolean;
  sources: { source: string; million?: number; note: string }[];
};

const AS_OF = "2026-08-17";

export const HUNT_SEEDS: HuntSeed[] = [
  {
    id: "haus24-ratchaphruek",
    name: "Haus 24 ราชพฤกษ์",
    developer: "Haus 24",
    zone: "ราชพฤกษ์–บางพลับ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: true,
    million: 5.53,
    millionMax: 11.1,
    priceNote: "ช่วงโครงการ 5.53–11.1 ลบ. บ้านเดี่ยว 191 ตร.ม. ต้องหาแปลงสุทธิ ≤6M",
    landNote: "50.8 ตร.ว.",
    landWahTenths: 508,
    usableSqmMin: 191,
    usableSqmMax: 191,
    bedrooms: 4,
    bathrooms: 3,
    parking: 2,
    fitScore: 92,
    valueScore: 4,
    rank: 1,
    commuteNote: "ห่างราชพฤกษ์ ~1 กม. ราชพฤกษ์ → กรุงธนบุรี → สาทร → สีลม พฤหัส–ศุกร์ ไม่ต้องวิ่งลึกบางใหญ่",
    sizeNote: "บ้านเดี่ยว 191 ตร.ม. / 50.8 ตร.ว. / 4 นอน 3 น้ำ 2 จอด — 64 ยูนิต",
    caveat: "ถ้าหาแปลงเดี่ยว ≤6M ได้ คือตัวเต็ง ข้อมูลเก่า 4.7–5 ลบ. ไม่ใช่ราคาปัจจุบัน",
    lat: "13.8770",
    lng: "100.4780",
    traffic: "yellow",
    hospitalNote: "ปากเกร็ด 2 / พระนั่งเกล้า / เกษมราษฎร์ รัตนาธิเบศร์",
    mallNote: "Lotus's North ราชพฤกษ์, Design Village, The Walk, Robinson ราชพฤกษ์, Central Westville / รัตนาธิเบศร์ / Westgate",
    highwayNote: "ราชพฤกษ์ ชัยพฤกษ์ รัตนาธิเบศร์ กาญจนาฯ",
    schoolNote: "",
    pros: "ทำเลเข้า ITF ดีที่สุดในกลุ่ม ห้างครบ บ้าน 191 ตร.ม.",
    cons: "ราคาแปลงเดี่ยวหลายยูนิตเกิน 6M",
    budgetUnder6: true,
    unitCheck: true,
    sources: [
      { source: "โครงการ", million: 5.53, note: "ช่วง 5.53–11.1 ลบ. บ้านเดี่ยว 191 ตร.ม. / 50.8 ตร.ว." },
    ],
  },
  {
    id: "parkville-kanchana-kantana",
    name: "ศุภาลัย พาร์ควิลล์ กาญจนาฯ–ซ.กันตนา",
    developer: "ศุภาลัย",
    zone: "กันตนา–กาญจนาฯ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 6,
    priceNote: "หน้าโครงการไม่โชว์ราคาเริ่ม — ต้องเช็กแปลงเดี่ยว ≤6M (โปรโซนนนทบุรีลดสูงสุด 1.2 ลบ.)",
    landNote: "บ้านเดี่ยว 2 ชั้น Tropical Style",
    landWahTenths: null,
    usableSqmMin: null,
    usableSqmMax: 295,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 90,
    valueScore: 4,
    rank: 2,
    commuteNote: "ออกซอยกันตนาหลายทาง เชื่อมกาญจนาฯ บรมราชชนนี ทางด่วนศรีรัช และ M81",
    sizeNote: "พื้นที่ใช้สอยสูงสุด 295 ตร.ม. มี Solar Cell และ Home Automation ทุกหลัง",
    caveat: "คนละโครงการกับ Bella กันตนา — บ้านใหญ่กว่าชัด ต้องเช็กราคาสุทธิ",
    lat: "13.8120",
    lng: "100.3950",
    traffic: "orange",
    hospitalNote: "ออกไปบางใหญ่ / ธนบุรี 2 ได้",
    mallNote: "Lotus บางใหญ่, Central Westgate, The Walk ราชพฤกษ์",
    highwayNote: "กาญจนาฯ บรมราชชนนี ศรีรัช M81",
    schoolNote: "",
    pros: "บ้าน/ที่ดินใหญ่ หลายทางออก ไม่ใช่กันตนาแบบตัน",
    cons: "ยังไม่มีราคาเริ่มจากหน้าเว็บ ระยะเข้า ITF แพ้ Haus 24 ราชพฤกษ์",
    budgetUnder6: true,
    unitCheck: true,
    sources: [{ source: "ศุภาลัย", note: "บ้านเดี่ยว Tropical สูงสุด 295 ตร.ม. Solar Cell + Home Automation" }],
  },
  {
    id: "pruklada-ratchaphruek-345",
    name: "พฤกษ์ลดา ราชพฤกษ์–345",
    developer: "Land & Houses",
    zone: "ราชพฤกษ์–345",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 5.49,
    millionMax: 8,
    priceNote: "แปลงหลุดโอน EARTH 5.49 ลบ. (เคยเริ่ม 6.29–8)",
    landNote: "51 ตร.ว.",
    landWahTenths: 510,
    usableSqmMin: 137,
    usableSqmMax: 137,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 89,
    valueScore: 5,
    rank: 3,
    commuteNote: "ถนน 345 ละหาร บางบัวทอง ออก 345 → ราชพฤกษ์ → กาญจนาฯ เข้าเมืองได้ แต่ไกลกว่า Haus 24 ราชพฤกษ์",
    sizeNote: "แปลงที่พบ 51 ตร.ว. / 137 ตร.ม.",
    caveat: "บ้านเล็กกว่า Haus 24 (~191 ตร.ม.) — ถ้า Haus 24 ≤6M แพ้พื้นที่ ถ้า Haus 24 6.5–7M ตัวนี้คุ้ม",
    lat: "13.9370",
    lng: "100.4250",
    traffic: "yellow",
    hospitalNote: "ออกปากเกร็ด รัตนาธิเบศร์ บางใหญ่ ได้",
    mallNote: "ออกราชพฤกษ์/ชัยพฤกษ์ได้ แต่ไม่ติดห้างใหญ่แบบ Westgate",
    highwayNote: "345 ราชพฤกษ์ กาญจนาฯ",
    schoolNote: "",
    pros: "ราคา 5.49M อยู่ในงบ L&H ทำเลสมดุล",
    cons: "ใช้สอย 137 ตร.ม. เล็กกว่า Haus 24",
    budgetUnder6: true,
    unitCheck: false,
    sources: [{ source: "LH", million: 5.49, note: "แปลง EARTH 51 ตร.ว. / 137 ตร.ม. จาก 6.29M" }],
  },
  {
    id: "haus24-westgate",
    name: "Haus 24 Westgate",
    developer: "Haus 24",
    zone: "บางคูรัด–Westgate",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 5.18,
    millionMax: 6.52,
    priceNote: "ตัวอย่างบ้าน 191 ตร.ม. ~5.18 ลบ. ช่วงโครงการ 3.56–6.52",
    landNote: "50 ตร.ว.",
    landWahTenths: 500,
    usableSqmMin: 162,
    usableSqmMax: 191,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 86,
    valueScore: 5,
    rank: 4,
    commuteNote: "กาญจนาฯ ลาดปลาดุก รัตนาธิเบศร์ M81 — อยู่บ้านทุกวันดี เข้า ITF 2 วัน/สัปดาห์ยอมได้ ไม่เหมาะเข้า 5 วัน",
    sizeNote: "มีแบบ 162 และ 191 ตร.ม. / 50 ตร.ว.",
    caveat: "King of Value แต่เข้าสีลมไกลกว่า Haus 24 ราชพฤกษ์",
    lat: "13.8560",
    lng: "100.4110",
    traffic: "orange",
    hospitalNote: "รพ.บางใหญ่ และโซนรัตนาธิเบศร์",
    mallNote: "Central Westgate IKEA Big C Lotus's Index HomePro",
    highwayNote: "กาญจนาภิเษก ลาดปลาดุก รัตนาธิเบศร์ M81",
    schoolNote: "",
    pros: "บ้านใหญ่ต่อเงิน ecosystem Westgate ครบ",
    cons: "ระยะเข้า ITF สีลมแพ้ราชพฤกษ์ ช่วงเร่งด่วนต้องเผื่อ",
    budgetUnder6: true,
    unitCheck: false,
    sources: [
      { source: "ประกาศ", million: 5.18, note: "บ้าน 191 ตร.ม. / 50 ตร.ว." },
      { source: "โครงการ", million: 3.56, note: "ช่วงรวม 3.56–6.52 ลบ." },
    ],
  },
  {
    id: "anasiri-pinklao-kanchana",
    name: "อณาสิริ ปิ่นเกล้า–กาญจนาฯ",
    developer: "Sansiri",
    zone: "กาญจนาฯ–บางกรวย",
    houseType: "mixed",
    hasDetached: true,
    hasTwin: true,
    million: 4.99,
    millionMax: 6,
    priceNote: "เริ่ม 4.99 ลบ. จากเว็บ Sansiri",
    landNote: "37–100 ตร.ว.",
    landWahTenths: 370,
    usableSqmMin: 152,
    usableSqmMax: 235,
    bedrooms: null,
    bathrooms: null,
    parking: 2,
    fitScore: 85,
    valueScore: 4,
    rank: 5,
    commuteNote: "ออก 3 เส้นทาง กาญจนาฯ 6.2 กม. บรมฯ 7.8 กม. นครอินทร์ 8 กม. ศรีรัชฉิมพลี 10.5 กม.",
    sizeNote: "ใช้สอย 152–235 ตร.ม. จอด 2–3 คัน",
    caveat: "เริ่มเข้าโซนบางกรวย/กาญจนาฯ ระยะ ITF ต่ำกว่า Haus 24 ราชพฤกษ์",
    lat: "13.8200",
    lng: "100.4300",
    traffic: "yellow",
    hospitalNote: "รพ.บางใหญ่ 6.6 กม. ธนบุรี 2 10.9 กม. ราชพิพัฒน์ 15.5 กม.",
    mallNote: "Lotus Plus บางใหญ่ 7.5 กม. Westgate 10.3 กม. The Walk 12.1 กม. Westville 14.2 กม. ศาลายา 14.7 กม.",
    highwayNote: "กาญจนาฯ บรมราชชนนี นครอินทร์ ศรีรัชด่านฉิมพลี",
    schoolNote: "เปรมประชา 5.3 กม. มหิดลวิทยานุสรณ์ 8.8 กม. เทพศิรินทร์ นนทบุรี 9 กม. สาธิตนานาชาติมหิดล 9.3 กม.",
    pros: "Sansiri ในงบ บ้านใหญ่ ทางออกหลายเส้น",
    cons: "ไกล ITF กว่าฝั่งราชพฤกษ์",
    budgetUnder6: true,
    unitCheck: false,
    sources: [{ source: "Sansiri", million: 4.99, note: "ที่ดิน 37–100 ตร.ว. ใช้สอย 152–235 ตร.ม." }],
  },
  {
    id: "palm-springs-chaiyapruek",
    name: "ศุภาลัย ปาล์มสปริงส์ ชัยพฤกษ์–แจ้งวัฒนะ",
    developer: "ศุภาลัย",
    zone: "ชัยพฤกษ์–แจ้งวัฒนะ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 4.59,
    priceNote: "ราคาเริ่มต้นล่าสุดที่พบ",
    landNote: "36.3–111.3 ตร.ว.",
    landWahTenths: 363,
    usableSqmMin: 154,
    usableSqmMax: 317,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 84,
    valueScore: 5,
    rank: 6,
    commuteNote: "ชัยพฤกษ์ → แจ้งวัฒนะ → กาญจนาฯ ออกเมืองได้หลายทาง แต่เช้าเย็นคอขวด",
    sizeNote: "บ้านใหญ่ 154–317 ตร.ม.",
    caveat: "บ้านใหญ่ ≠ เดินทางดีกว่า Haus 24 ราชพฤกษ์",
    lat: "13.9050",
    lng: "100.5280",
    traffic: "orange",
    hospitalNote: "โซนแจ้งวัฒนะ / ปากเกร็ด",
    mallNote: "Central แจ้งวัฒนะ Lotus's HomePro Robinson ออก Westville / Westgate ได้",
    highwayNote: "ชัยพฤกษ์ แจ้งวัฒนะ กาญจนาฯ",
    schoolNote: "",
    pros: "เงิน 4.5–5M ได้บ้านใหญ่สุดกลุ่ม",
    cons: "แจ้งวัฒนะ/ชัยพฤกษ์ ติดช่วงเร่งด่วน เข้า ITF ไม่เท่าราชพฤกษ์",
    budgetUnder6: true,
    unitCheck: false,
    sources: [{ source: "ศุภาลัย", million: 4.59, note: "ที่ดิน 36.3–111.3 ตร.ว." }],
  },
  {
    id: "lumpini-kaew-in",
    name: "บ้านลุมพินี แก้วอินทร์",
    developer: "LPN",
    zone: "แก้วอินทร์–บางใหญ่",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 4.89,
    millionMax: 8.74,
    priceNote: "เปิดตัว 4.89 ลบ. ประกาศขายที่พบราว 5.715–8.744",
    landNote: "50 ตร.ว.",
    landWahTenths: 500,
    usableSqmMin: 187,
    usableSqmMax: 191,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    fitScore: 82,
    valueScore: 4,
    rank: 7,
    commuteNote: "ติดมอเตอร์เวย์บางใหญ่ / M81 ใกล้ Westgate — ชีวิต Westgate ดี เข้า ITF สีลมเสียเปรียบราชพฤกษ์",
    sizeNote: "Type A 191 / Type B 187 ตร.ม. 3 นอน 3 น้ำ 2 จอด",
    caveat: "LPN บ้านเดี่ยวในโซนนี้มีน้อย — เก็บตัวนี้ ไม่เอา Townville มาเทียบเดี่ยว",
    lat: "13.8500",
    lng: "100.4050",
    traffic: "red",
    hospitalNote: "รพ.บางใหญ่",
    mallNote: "Central Westgate",
    highwayNote: "M81 กาญจนาฯ",
    schoolNote: "",
    pros: "บ้านไซส์ดี ราคาเปิดตัวอยู่ในงบ ติดทางด่วน/ห้าง",
    cons: "เข้าเมืองสีลมบ่อยจะเสียเวลา",
    budgetUnder6: true,
    unitCheck: false,
    sources: [
      { source: "LPN", million: 4.89, note: "บ้านเดี่ยว 50 ตร.ว. เปิดตัว" },
      { source: "ประกาศขาย", note: "ประมาณ 5.715–8.744 ลบ." },
    ],
  },
  {
    id: "bella-kanchana-kantana",
    name: "ศุภาลัย เบลล่า กาญจนาฯ–กันตนา",
    developer: "ศุภาลัย",
    zone: "กันตนา–กาญจนาฯ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 4.19,
    millionMax: 8.59,
    priceNote: "เริ่ม ~4.19 ลบ. บ้านตัวอย่าง 6.69 และ 8.59",
    landNote: "เริ่ม 35 ตร.ว.",
    landWahTenths: 350,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 79,
    valueScore: 5,
    rank: 8,
    commuteNote: "กาญจนาฯ–ซอยกันตนา — ประหยัดกว่า Park Ville แต่บ้านเล็กกว่า",
    sizeNote: "เริ่ม 35 ตร.ว. มีบ้านเดี่ยวหลายแบบ",
    caveat: "คนละโครงการกับพาร์ควิลล์ — อย่าปน",
    lat: "13.8080",
    lng: "100.3980",
    traffic: "red",
    hospitalNote: "ออกบางใหญ่ได้",
    mallNote: "Lotus บางใหญ่ / Westgate",
    highwayNote: "กาญจนาฯ",
    schoolNote: "",
    pros: "ราคาเข้าถึงง่าย",
    cons: "เล็กกว่า Park Ville เข้าเมืองบ่อยไม่เหมาะ",
    budgetUnder6: true,
    unitCheck: false,
    sources: [
      { source: "ศุภาลัย", million: 4.19, note: "เริ่ม 35 ตร.ว." },
      { source: "บ้านตัวอย่าง", note: "6.69 และ 8.59 ลบ." },
    ],
  },
  {
    id: "pride-bangyai",
    name: "ศุภาลัย ไพร์ด บางใหญ่",
    developer: "ศุภาลัย",
    zone: "บางใหญ่",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 3.39,
    priceNote: "ราคาเริ่มต้นจากศุภาลัย",
    landNote: "",
    landWahTenths: null,
    usableSqmMin: 126,
    usableSqmMax: 190,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 78,
    valueScore: 5,
    rank: 9,
    commuteNote: "บางใหญ่ใกล้ Westgate — ถูกสุดกลุ่ม แต่ไกล routine เข้า ITF",
    sizeNote: "126–190 ตร.ม.",
    caveat: "ราคาถูกแต่ทำเลเข้าเมืองเป็นจุดอ่อน",
    lat: "13.8780",
    lng: "100.4080",
    traffic: "red",
    hospitalNote: "รพ.บางใหญ่",
    mallNote: "Central Westgate",
    highwayNote: "กาญจนาฯ M81",
    schoolNote: "",
    pros: "ถูกสุดในลิสต์",
    cons: "ไกลสำหรับเข้าสีลม",
    budgetUnder6: true,
    unitCheck: false,
    sources: [{ source: "ศุภาลัย", million: 3.39, note: "ใช้สอย 126–190 ตร.ม." }],
  },
  {
    id: "anasiri-ratchaphruek-345",
    name: "อณาสิริ ราชพฤกษ์–345",
    developer: "Sansiri",
    zone: "ราชพฤกษ์–345",
    houseType: "mixed",
    hasDetached: true,
    hasTwin: true,
    million: 5,
    millionMax: 7,
    priceNote: "ประมาณ 5–7 ลบ.",
    landNote: "",
    landWahTenths: null,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 86,
    valueScore: 4,
    rank: 10,
    commuteNote: "ราชพฤกษ์–345 เชื่อมหลายทาง ถ้างบขยับถึง 6.5–7 น่าดู",
    sizeNote: "บ้านเดี่ยว/บ้านแฝด",
    caveat: "บางแปลงอาจเกิน 6M",
    lat: "13.9200",
    lng: "100.4450",
    traffic: "yellow",
    hospitalNote: "ปากเกร็ด / รัตนาธิเบศร์",
    mallNote: "ออกราชพฤกษ์/ชัยพฤกษ์",
    highwayNote: "ราชพฤกษ์ 345 กาญจนาฯ",
    schoolNote: "",
    pros: "Sansiri ทำเลสมดุลใกล้ 345",
    cons: "ช่วงราคาทับงบบน",
    budgetUnder6: false,
    unitCheck: true,
    sources: [{ source: "ประมาณการ", million: 5, note: "ช่วง ~5–7 ลบ." }],
  },
  {
    id: "saransiri-ratchaphruek-chaeng",
    name: "สราญสิริ ราชพฤกษ์–แจ้งวัฒนะ",
    developer: "Sansiri",
    zone: "ราชพฤกษ์–แจ้งวัฒนะ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 6,
    millionMax: 8,
    priceNote: "ประมาณ 6–8 ลบ.",
    landNote: "",
    landWahTenths: null,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 87,
    valueScore: 3,
    rank: 11,
    commuteNote: "ราชพฤกษ์–แจ้งวัฒนะ แบรนด์/บรรยากาศดี งบเริ่มชนเพดาน 6M",
    sizeNote: "บ้านเดี่ยว",
    caveat: "เน้นอณาสิริ/สราญสิริ มากกว่าเศรษฐสิริ",
    lat: "13.8950",
    lng: "100.5000",
    traffic: "orange",
    hospitalNote: "ปากเกร็ด / แจ้งวัฒนะ",
    mallNote: "Central แจ้งวัฒนะ / Westville",
    highwayNote: "ราชพฤกษ์ แจ้งวัฒนะ",
    schoolNote: "",
    pros: "Sansiri บรรยากาศและทำเลราชพฤกษ์",
    cons: "งบ 6–8M อาจเกินเพดาน",
    budgetUnder6: false,
    unitCheck: true,
    sources: [{ source: "ประมาณการ", million: 6, note: "ช่วง ~6–8 ลบ." }],
  },
  {
    id: "centro-ratchaphruek-pinklao",
    name: "CENTRO ราชพฤกษ์–ปิ่นเกล้า",
    developer: "AP",
    zone: "ราชพฤกษ์–ปิ่นเกล้า",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 8.99,
    priceNote: "ราคาเริ่มต้นที่พบ — ซื้อทำเลมากกว่าซื้อพื้นที่",
    landNote: "50.3–118.7 ตร.ว.",
    landWahTenths: 503,
    usableSqmMin: 193,
    usableSqmMax: 274,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 93,
    valueScore: 3,
    rank: 12,
    commuteNote: "ทำเลดีที่สุดในกลุ่มกว้าง ราชพฤกษ์ตัดใหม่ เข้าศรีรัช — ถ้างบเกิน 8 ลบ. กลับมาน่าสนใจ",
    sizeNote: "193–274 ตร.ม.",
    caveat: "นอกงบ ≤6M",
    lat: "13.7900",
    lng: "100.4550",
    traffic: "yellow",
    hospitalNote: "โซนปิ่นเกล้า / จรัญ",
    mallNote: "Central ปิ่นเกล้า / The Walk ราชพฤกษ์",
    highwayNote: "ราชพฤกษ์ ศรีรัชด่านราชพฤกษ์",
    schoolNote: "",
    pros: "ทำเลเข้าเมืองดีสุดกลุ่ม",
    cons: "ราคาแรง 8.99M+",
    budgetUnder6: false,
    unitCheck: false,
    sources: [{ source: "AP", million: 8.99, note: "ที่ดิน 50.3–118.7 ตร.ว." }],
  },
  {
    id: "setthasiri-ratchaphruek-charan",
    name: "เศรษฐสิริ ราชพฤกษ์–จรัญฯ",
    developer: "Sansiri",
    zone: "ราชพฤกษ์–จรัญฯ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 10,
    priceNote: "ประมาณ 10 ลบ. ขึ้นไป",
    landNote: "",
    landWahTenths: null,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 88,
    valueScore: 2,
    rank: 13,
    commuteNote: "ทำเลดีเข้าเมือง แต่เกินงบ 4–6M ชัด",
    sizeNote: "บ้านเดี่ยว",
    caveat: "เก็บในตารางรวม ไม่ใช่ shortlist งบ 6M",
    lat: "13.7700",
    lng: "100.4680",
    traffic: "yellow",
    hospitalNote: "โซนจรัญ / ปิ่นเกล้า",
    mallNote: "Central ปิ่นเกล้า",
    highwayNote: "ราชพฤกษ์ จรัญฯ",
    schoolNote: "",
    pros: "ทำเลและแบรนด์",
    cons: "เกินงบมาก",
    budgetUnder6: false,
    unitCheck: false,
    sources: [{ source: "ประมาณการ", million: 10, note: "~10 ลบ.+" }],
  },
  {
    id: "villaggio-bangyai",
    name: "Villaggio บางใหญ่",
    developer: "Land & Houses",
    zone: "บางใหญ่",
    houseType: "mixed",
    hasDetached: true,
    hasTwin: true,
    million: 4,
    millionMax: 5,
    priceNote: "บ้านเดี่ยว/บ้านคู่ ประมาณ 4–5 ลบ.",
    landNote: "ใกล้ Central Westgate",
    landWahTenths: null,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 80,
    valueScore: 4,
    rank: 14,
    commuteNote: "ใกล้ Westgate เชื่อมกาญจนาฯ",
    sizeNote: "เช็กแบบต่อแปลง",
    caveat: "ช่วงราคาประมาณการ",
    lat: "13.8620",
    lng: "100.4150",
    traffic: "orange",
    hospitalNote: "รพ.บางใหญ่",
    mallNote: "Central Westgate",
    highwayNote: "กาญจนาฯ",
    schoolNote: "",
    pros: "L&H ใกล้ห้าง",
    cons: "เข้า ITF ไม่เด่น",
    budgetUnder6: true,
    unitCheck: true,
    sources: [{ source: "LH", million: 4, note: "~4–5 ลบ." }],
  },
  {
    id: "pruklada-pinklao-salaya",
    name: "พฤกษ์ลดา ปิ่นเกล้า–ศาลายา",
    developer: "Land & Houses",
    zone: "ศาลายา",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 5.99,
    priceNote: "LH ระบุปัจจุบัน",
    landNote: "เริ่ม 50 ตร.ว.",
    landWahTenths: 500,
    usableSqmMin: 137,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 79,
    valueScore: 4,
    rank: 15,
    commuteNote: "บ้านดี แต่ไกลเส้นทาง ITF กว่าราชพฤกษ์–345",
    sizeNote: "ที่ดินเริ่ม 50 ตร.ว. ใช้สอยเริ่ม 137 ตร.ม.",
    caveat: "อยู่นอก shortlist เข้าเมือง",
    lat: "13.8020",
    lng: "100.3250",
    traffic: "orange",
    hospitalNote: "ศาลายา / ศิริราช ศาลายา",
    mallNote: "Central ศาลายา",
    highwayNote: "บรมราชชนนี",
    schoolNote: "",
    pros: "คุณภาพบ้าน L&H",
    cons: "ไกลสีลม",
    budgetUnder6: true,
    unitCheck: false,
    sources: [{ source: "LH", million: 5.99, note: "ที่ดินเริ่ม 50 ตร.ว." }],
  },
  {
    id: "supalai-ville-ratchaphruek-kanchana",
    name: "ศุภาลัย วิลล์ ราชพฤกษ์–กาญจนาฯ",
    developer: "ศุภาลัย",
    zone: "ราชพฤกษ์–กาญจนาฯ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 4.99,
    priceNote: "บ้านเดี่ยวเริ่มประมาณ 4.99 ลบ.",
    landNote: "39.1–87.6 ตร.ว.",
    landWahTenths: 391,
    usableSqmMin: 138,
    usableSqmMax: 254,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 81,
    valueScore: 4,
    rank: 16,
    commuteNote: "เชื่อม 345 กาญจนาฯ ราชพฤกษ์ — ราคาดี แต่ไกลกว่า Haus 24 ราชพฤกษ์",
    sizeNote: "138–254 ตร.ม.",
    caveat: "ราคาเริ่มโครงการกับบ้านเดี่ยวคนละตัวเลข",
    lat: "13.8550",
    lng: "100.4450",
    traffic: "orange",
    hospitalNote: "รัตนาธิเบศร์ / บางใหญ่",
    mallNote: "ออก Westgate / ราชพฤกษ์ ได้",
    highwayNote: "กาญจนาฯ ราชพฤกษ์ 345",
    schoolNote: "",
    pros: "บ้านคุ้มราคา",
    cons: "ทำเลเข้า ITF รอง",
    budgetUnder6: true,
    unitCheck: false,
    sources: [{ source: "แบบบ้าน", million: 4.99, note: "บ้านเดี่ยว ~4.99 ลบ." }],
  },
  {
    id: "ville-chaiyapruek-ring",
    name: "ศุภาลัย วิลล์ ชัยพฤกษ์–วงแหวน",
    developer: "ศุภาลัย",
    zone: "ชัยพฤกษ์–วงแหวน",
    houseType: "mixed",
    hasDetached: true,
    hasTwin: true,
    million: 4.09,
    priceNote: "บ้านเดี่ยวไซส์ใหญ่เริ่ม 4.09 ลบ. แฝดเริ่ม 2.99",
    landNote: "บ้านเดี่ยวไซส์ใหญ่",
    landWahTenths: null,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 80,
    valueScore: 5,
    rank: 17,
    commuteNote: "ชัยพฤกษ์–วงแหวน",
    sizeNote: "มีทั้งเดี่ยวและแฝด",
    caveat: "อย่าดูราคาแฝดถ้าต้องการเดี่ยว",
    lat: "13.9150",
    lng: "100.5100",
    traffic: "orange",
    hospitalNote: "แจ้งวัฒนะ / ปากเกร็ด",
    mallNote: "Central แจ้งวัฒนะ",
    highwayNote: "ชัยพฤกษ์ วงแหวน",
    schoolNote: "",
    pros: "ราคา/พื้นที่ดี",
    cons: "เข้า ITF ไม่เด่น",
    budgetUnder6: true,
    unitCheck: false,
    sources: [{ source: "ศุภาลัย", million: 4.09, note: "แฝดเริ่ม 2.99 ลบ." }],
  },
  {
    id: "ville-pinklao-salaya",
    name: "ศุภาลัย วิลล์ ปิ่นเกล้า–ศาลายา",
    developer: "ศุภาลัย",
    zone: "ศาลายา",
    houseType: "mixed",
    hasDetached: true,
    hasTwin: true,
    million: 4.59,
    millionMax: 6.29,
    priceNote: "ข้อมูลล่าสุดที่พบเป็นบ้านแฝด 4.59 ข้อมูลเก่า 5.29–6.29",
    landNote: "แฝด 45.5–47.9 ตร.ว.",
    landWahTenths: 455,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 77,
    valueScore: 4,
    rank: 18,
    commuteNote: "ศาลายา — เช็กบ้านเดี่ยวที่เหลือเป็นแปลง ๆ",
    sizeNote: "ต้องเช็กแบบเดี่ยว",
    caveat: "อย่าใช้ราคาแฝดแทนเดี่ยว",
    lat: "13.8050",
    lng: "100.3400",
    traffic: "orange",
    hospitalNote: "ศาลายา",
    mallNote: "Central ศาลายา",
    highwayNote: "บรมราชชนนี",
    schoolNote: "",
    pros: "ราคาเริ่มต่ำถ้าเป็นแฝด",
    cons: "ไกล ITF แบบเดี่ยวไม่ชัด",
    budgetUnder6: true,
    unitCheck: true,
    sources: [{ source: "Home.co.th", million: 4.59, note: "บ้านแฝด" }],
  },
  {
    id: "lumpini-townville-ratchaphruek",
    name: "ลุมพินี ทาวน์วิลล์ ราชพฤกษ์–ปิ่นเกล้า",
    developer: "LPN",
    zone: "ราชพฤกษ์–ปิ่นเกล้า",
    houseType: "twin",
    hasDetached: false,
    hasTwin: true,
    million: 4.89,
    priceNote: "เฟส 2 เคยเริ่มสุทธิ 4.89 ลบ.",
    landNote: "เริ่มประมาณ 35 ตร.ว.",
    landWahTenths: 350,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 80,
    valueScore: 4,
    rank: 19,
    commuteNote: "ทำเลดีใกล้ทางด่วนศรีรัช/ด่านราชพฤกษ์ แต่เป็นบ้านแฝด ไม่เทียบตรงกับเดี่ยว",
    sizeNote: "บ้านแฝด",
    caveat: "ไม่ใส่เทียบบ้านเดี่ยว",
    lat: "13.7850",
    lng: "100.4500",
    traffic: "yellow",
    hospitalNote: "ปิ่นเกล้า / จรัญ",
    mallNote: "shopping ราชพฤกษ์",
    highwayNote: "ศรีรัชด่านราชพฤกษ์",
    schoolNote: "",
    pros: "ทำเลราชพฤกษ์–ปิ่นเกล้า",
    cons: "ไม่ใช่บ้านเดี่ยว",
    budgetUnder6: true,
    unitCheck: false,
    sources: [{ source: "LPN", million: 4.89, note: "บ้านแฝด เริ่ม ~35 ตร.ว." }],
  },
  {
    id: "siriplace-ratchaphruek-345",
    name: "สิริเพลส ราชพฤกษ์–345",
    developer: "Sansiri",
    zone: "ราชพฤกษ์–345",
    houseType: "twin",
    hasDetached: false,
    hasTwin: true,
    million: 3,
    millionMax: 5,
    priceNote: "ประมาณ 3–5 ลบ. บ้านแฝด",
    landNote: "",
    landWahTenths: null,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 80,
    valueScore: 4,
    rank: 20,
    commuteNote: "ราชพฤกษ์–345 ประหยัด แต่ไม่ใช่บ้านเดี่ยว",
    sizeNote: "บ้านแฝด",
    caveat: "กรองบ้านเดี่ยวเท่านั้นจะซ่อน",
    lat: "13.9250",
    lng: "100.4300",
    traffic: "yellow",
    hospitalNote: "ปากเกร็ด",
    mallNote: "ออกราชพฤกษ์",
    highwayNote: "ราชพฤกษ์ 345",
    schoolNote: "",
    pros: "ราคาประหยัด ทำเล 345",
    cons: "บ้านแฝด",
    budgetUnder6: true,
    unitCheck: true,
    sources: [{ source: "ประมาณการ", million: 3, note: "แฝด ~3–5 ลบ." }],
  },
];

export function seedRows() {
  return HUNT_SEEDS.map((s) => ({
    id: s.id,
    name: s.name,
    developer: s.developer,
    zone: s.zone,
    houseType: s.houseType,
    hasDetached: s.hasDetached,
    hasTwin: s.hasTwin,
    priceStartSatang: satangFromMillion(s.million),
    priceMaxSatang: s.millionMax != null ? satangFromMillion(s.millionMax) : null,
    priceNote: s.priceNote,
    landNote: s.landNote,
    landWahTenths: s.landWahTenths,
    usableSqmMin: s.usableSqmMin,
    usableSqmMax: s.usableSqmMax,
    bedrooms: s.bedrooms,
    bathrooms: s.bathrooms,
    parking: s.parking,
    fitScore: s.fitScore,
    valueScore: s.valueScore,
    rank: s.rank,
    commuteNote: s.commuteNote,
    sizeNote: s.sizeNote,
    caveat: s.caveat,
    lat: s.lat,
    lng: s.lng,
    traffic: s.traffic,
    hospitalNote: s.hospitalNote,
    mallNote: s.mallNote,
    highwayNote: s.highwayNote,
    schoolNote: s.schoolNote,
    pros: s.pros,
    cons: s.cons,
    budgetUnder6: s.budgetUnder6,
    unitCheck: s.unitCheck,
  }));
}

export function seedPriceNotes() {
  return HUNT_SEEDS.flatMap((s) =>
    s.sources.map((src, i) => ({
      id: `${s.id}-src-${i}`,
      projectId: s.id,
      source: src.source,
      priceSatang: src.million != null ? satangFromMillion(src.million) : null,
      note: src.note,
      asOf: AS_OF,
    })),
  );
}
