import { satangFromMillion } from "./format";

export type HuntSeed = {
  id: string;
  name: string;
  developer: string;
  zone: string;
  houseType: "detached" | "twin" | "mixed";
  hasDetached: boolean;
  hasTwin: boolean;
  million: number;
  priceNote: string;
  landNote: string;
  landWahTenths: number | null;
  usableSqmMin: number | null;
  usableSqmMax: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  parking: number | null;
  fitScore: number;
  valueScore: number;
  rank: number;
  commuteNote: string;
  sizeNote: string;
  caveat: string;
  sources: { source: string; million?: number; note: string }[];
};

const AS_OF = "2026-08-01";

export const HUNT_SEEDS: HuntSeed[] = [
  {
    id: "centro-ratchaphruek-pinklao",
    name: "CENTRO ราชพฤกษ์–ปิ่นเกล้า",
    developer: "AP",
    zone: "ราชพฤกษ์–ปิ่นเกล้า",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 8.99,
    priceNote: "ราคาเริ่มต้นที่พบ",
    landNote: "50.3–118.7 ตร.ว.",
    landWahTenths: 503,
    usableSqmMin: 193,
    usableSqmMax: 274,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 93,
    valueScore: 3,
    rank: 1,
    commuteNote: "ราชพฤกษ์ตัดใหม่ เข้าศรีรัช/ด่านราชพฤกษ์ — เหมาะรถเข้า ITF/สีลม 2 วันต่อสัปดาห์",
    sizeNote: "ที่ดิน 50.3–118.7 ตร.ว. พื้นที่ใช้สอย 193–274 ตร.ม.",
    caveat: "งบสูงกว่า 4–5 ลบ. ชัดเจน",
    sources: [{ source: "AP", million: 8.99, note: "ที่ดิน 50.3–118.7 ตร.ว. พื้นที่ใช้สอยประมาณ 193–274 ตร.ม." }],
  },
  {
    id: "supalai-ville-ratchaphruek-kanchana",
    name: "ศุภาลัย วิลล์ ราชพฤกษ์–กาญจนาฯ",
    developer: "ศุภาลัย",
    zone: "ราชพฤกษ์–กาญจนาฯ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 4.99,
    priceNote: "บ้านเดี่ยวเริ่มประมาณ 4.99 ลบ. (โครงการอาจเริ่ม 3.69–3.79)",
    landNote: "39.1–87.6 ตร.ว.",
    landWahTenths: 391,
    usableSqmMin: 138,
    usableSqmMax: 254,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 91,
    valueScore: 5,
    rank: 2,
    commuteNote: "เชื่อม 345 + กาญจนาฯ + ราชพฤกษ์ตัดใหม่ ได้หลายทาง",
    sizeNote: "บ้านเดี่ยว 138–254 ตร.ม. ที่ดิน 39.1–87.6 ตร.ว.",
    caveat: "ราคาเริ่มโครงการกับราคาบ้านเดี่ยวคนละตัวเลข — ต้องขอแปลงจริง",
    sources: [
      { source: "ศุภาลัย", million: 3.69, note: "ราคาเริ่มต้นโครงการราว 3.69–3.79 ลบ." },
      { source: "แบบบ้าน", million: 4.99, note: "บ้านเดี่ยวเริ่มประมาณ 4.99 ลบ." },
    ],
  },
  {
    id: "haus24-ratchaphruek",
    name: "Haus 24 ราชพฤกษ์",
    developer: "Haus 24",
    zone: "ราชพฤกษ์–บางพลับ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: true,
    million: 5,
    priceNote: "บ้านเดี่ยวระดับ 5 ลบ. ขึ้นไป",
    landNote: "50 ตร.ว.",
    landWahTenths: 500,
    usableSqmMin: 191,
    usableSqmMax: 191,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 90,
    valueScore: 4,
    rank: 3,
    commuteNote: "ราชพฤกษ์–บางพลับ ใกล้เส้นเข้าเมืองฝั่งปิ่นเกล้า",
    sizeNote: "บ้านเดี่ยว 50 ตร.ว. / 191 ตร.ม.",
    caveat: "เคยพบบ้านแฝดเริ่ม 5.79 ลบ. — เช็กราคาแปลงปัจจุบัน",
    sources: [{ source: "โครงการ", million: 5, note: "บ้านเดี่ยว 50 ตร.ว. / 191 ตร.ม." }],
  },
  {
    id: "pruklada-ratchaphruek-345",
    name: "พฤกษ์ลดา ราชพฤกษ์–345",
    developer: "Land & Houses",
    zone: "ราชพฤกษ์–345",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 6.29,
    priceNote: "LH ระบุ 6.29–8 ลบ.",
    landNote: "เริ่ม 50 ตร.ว.",
    landWahTenths: 500,
    usableSqmMin: 137,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 89,
    valueScore: 4,
    rank: 4,
    commuteNote: "ตรงกลาง Haus 24 ราชพฤกษ์ กับ Westgate — เชื่อม ราชพฤกษ์ / 345 / กาญจนาฯ / ชัยพฤกษ์",
    sizeNote: "ที่ดินเริ่ม 50 ตร.ว. พื้นที่ใช้สอยเริ่ม 137 ตร.ม.",
    caveat: "สูงกว่า Haus 24 Westgate ประมาณ 1.8 ลบ. — เทียบกับ Haus 24 ราชพฤกษ์ถ้างบถึง 6.5",
    sources: [{ source: "LH", million: 6.29, note: "6.29–8 ลบ. ที่ดินเริ่ม 50 ตร.ว." }],
  },
  {
    id: "palm-springs-chaiyapruek",
    name: "ศุภาลัย ปาล์มสปริงส์ ชัยพฤกษ์–แจ้งวัฒนะ",
    developer: "ศุภาลัย",
    zone: "ชัยพฤกษ์–แจ้งวัฒนะ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 4.59,
    priceNote: "ราคาเริ่มต้นล่าสุดที่พบ",
    landNote: "36.3–111.3 ตร.ว.",
    landWahTenths: 363,
    usableSqmMin: 154,
    usableSqmMax: 317,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 88,
    valueScore: 5,
    rank: 5,
    commuteNote: "ชัยพฤกษ์–แจ้งวัฒนะ ออกวงแหวน/เมืองได้",
    sizeNote: "ที่ดิน 36.3–111.3 ตร.ว. พื้นที่ใช้สอย 154–317 ตร.ม.",
    caveat: "ที่ดินเริ่มเล็กกว่า 50 ตร.ว. บางแปลง",
    sources: [{ source: "ศุภาลัย", million: 4.59, note: "ที่ดิน 36.3–111.3 ตร.ว." }],
  },
  {
    id: "haus24-westgate",
    name: "Haus 24 Westgate",
    developer: "Haus 24",
    zone: "บางคูรัด–Westgate",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 4.49,
    priceNote: "ราคาเริ่มต้นที่พบ",
    landNote: "50 ตร.ว.",
    landWahTenths: 500,
    usableSqmMin: 191,
    usableSqmMax: 191,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 85,
    valueScore: 5,
    rank: 6,
    commuteNote: "ใกล้ Central Westgate เชื่อมกาญจนาฯ",
    sizeNote: "บ้านเดี่ยว 50 ตร.ว. / 191 ตร.ม.",
    caveat: "ทำเล Westgate ดีต่อชีวิตประจำวัน แต่เข้า ITF ไกลกว่าราชพฤกษ์",
    sources: [{ source: "โครงการ", million: 4.49, note: "บ้านเดี่ยวเริ่ม 50 ตร.ว. / 191 ตร.ม." }],
  },
  {
    id: "lumpini-kaew-in",
    name: "บ้านลุมพินี แก้วอินทร์",
    developer: "LPN",
    zone: "แก้วอินทร์–บางใหญ่",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 4.89,
    priceNote: "บ้านเดี่ยว 50 ตร.ว.",
    landNote: "50 ตร.ว.",
    landWahTenths: 500,
    usableSqmMin: 187,
    usableSqmMax: 191,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    fitScore: 85,
    valueScore: 4,
    rank: 7,
    commuteNote: "ติด M81 / กาญจนาฯ ใกล้ Central Westgate",
    sizeNote: "Type A 191 ตร.ม. / Type B 187 ตร.ม. — 3 นอน 3 น้ำ 2 จอด",
    caveat: "ประกาศขายที่พบราว 5.715–8.744 ลบ. ต่างจากราคาเริ่มโครงการ",
    sources: [
      { source: "LPN", million: 4.89, note: "บ้านเดี่ยว 50 ตร.ว." },
      { source: "ประกาศขาย", note: "ประมาณ 5.715–8.744 ลบ." },
    ],
  },
  {
    id: "villaggio-bangyai",
    name: "Villaggio บางใหญ่",
    developer: "Land & Houses",
    zone: "บางใหญ่",
    houseType: "mixed",
    hasDetached: true,
    hasTwin: true,
    million: 4,
    priceNote: "บ้านเดี่ยว/บ้านคู่ ประมาณ 4–5 ลบ.",
    landNote: "ใกล้ Central Westgate",
    landWahTenths: null,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 84,
    valueScore: 4,
    rank: 8,
    commuteNote: "ใกล้ Central Westgate เชื่อมกาญจนาฯ",
    sizeNote: "บ้านเดี่ยวและบ้านคู่ — เช็กแบบต่อแปลง",
    caveat: "ช่วงราคาประมาณการ ต้องขอใบราคาปัจจุบัน",
    sources: [{ source: "LH", million: 4, note: "บ้านเดี่ยว/บ้านคู่ ~4–5 ลบ." }],
  },
  {
    id: "bella-kanchana-kantana",
    name: "ศุภาลัย เบลล่า กาญจนาฯ–กันตนา",
    developer: "ศุภาลัย",
    zone: "กันตนา–กาญจนาฯ",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 4.19,
    priceNote: "ราคาเริ่มต้นที่พบ — บ้านตัวอย่าง 6.69 และ 8.59 ลบ.",
    landNote: "เริ่ม 35 ตร.ว.",
    landWahTenths: 350,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 84,
    valueScore: 5,
    rank: 9,
    commuteNote: "กาญจนาฯ–ซอยกันตนา",
    sizeNote: "เริ่ม 35 ตร.ว. มีบ้านเดี่ยวหลายแบบ",
    caveat: "ราคาเริ่มกับบ้านตัวอย่างห่างกันมาก",
    sources: [
      { source: "ศุภาลัย", million: 4.19, note: "เริ่ม 35 ตร.ว." },
      { source: "บ้านตัวอย่าง", note: "6.69 และ 8.59 ลบ." },
    ],
  },
  {
    id: "pride-bangyai",
    name: "ศุภาลัย ไพร์ด บางใหญ่",
    developer: "ศุภาลัย",
    zone: "บางใหญ่",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 3.39,
    priceNote: "ราคาเริ่มต้นจากศุภาลัย",
    landNote: "",
    landWahTenths: null,
    usableSqmMin: 126,
    usableSqmMax: 190,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 83,
    valueScore: 5,
    rank: 10,
    commuteNote: "บางใหญ่ — ใกล้ Westgate กว่าฝั่งราชพฤกษ์",
    sizeNote: "126–190 ตร.ม. มีทั้งบ้านเดี่ยว/บ้านรุ่นใหม่",
    caveat: "ราคาเริ่มถูกสุดในลิสต์ — เช็กไซส์แปลงที่เหลือ",
    sources: [{ source: "ศุภาลัย", million: 3.39, note: "พื้นที่ใช้สอย 126–190 ตร.ม." }],
  },
  {
    id: "ville-chaiyapruek-ring",
    name: "ศุภาลัย วิลล์ ชัยพฤกษ์–วงแหวน",
    developer: "ศุภาลัย",
    zone: "ชัยพฤกษ์–วงแหวน",
    houseType: "mixed",
    hasDetached: true,
    hasTwin: true,
    million: 4.09,
    priceNote: "บ้านเดี่ยวไซส์ใหญ่เริ่ม 4.09 ลบ. บ้านแฝดเริ่ม 2.99 ลบ.",
    landNote: "บ้านเดี่ยวไซส์ใหญ่",
    landWahTenths: null,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 81,
    valueScore: 5,
    rank: 11,
    commuteNote: "ชัยพฤกษ์–วงแหวน",
    sizeNote: "บ้านเดี่ยวไซส์ใหญ่ / มีบ้านแฝด",
    caveat: "ถ้าต้องการเดี่ยวเท่านั้น อย่าดูราคาแฝด 2.99",
    sources: [{ source: "โปรโมชั่นศุภาลัย", million: 4.09, note: "แฝดเริ่ม 2.99 ลบ." }],
  },
  {
    id: "pruklada-pinklao-salaya",
    name: "พฤกษ์ลดา ปิ่นเกล้า–ศาลายา",
    developer: "Land & Houses",
    zone: "ศาลายา",
    houseType: "detached",
    hasDetached: true,
    hasTwin: false,
    million: 5.99,
    priceNote: "LH ระบุปัจจุบัน",
    landNote: "เริ่ม 50 ตร.ว.",
    landWahTenths: 500,
    usableSqmMin: 137,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 79,
    valueScore: 4,
    rank: 12,
    commuteNote: "บ้านดี แต่ไกล ITF กว่าราชพฤกษ์–345",
    sizeNote: "ที่ดินเริ่ม 50 ตร.ว. พื้นที่ใช้สอยเริ่ม 137 ตร.ม.",
    caveat: "ทำเลศาลายา เข้าออฟฟิศสีลมนานกว่าฝั่งราชพฤกษ์",
    sources: [{ source: "LH", million: 5.99, note: "ที่ดินเริ่ม 50 ตร.ว." }],
  },
  {
    id: "ville-pinklao-salaya",
    name: "ศุภาลัย วิลล์ ปิ่นเกล้า–ศาลายา",
    developer: "ศุภาลัย",
    zone: "ศาลายา",
    houseType: "mixed",
    hasDetached: true,
    hasTwin: true,
    million: 4.59,
    priceNote: "ข้อมูลล่าสุดที่พบเป็นบ้านแฝด",
    landNote: "แฝด 45.5–47.9 ตร.ว.",
    landWahTenths: 455,
    usableSqmMin: null,
    usableSqmMax: null,
    bedrooms: null,
    bathrooms: null,
    parking: null,
    fitScore: 77,
    valueScore: 4,
    rank: 13,
    commuteNote: "ศาลายา — เช็กบ้านเดี่ยวที่เหลือเป็นแปลง ๆ",
    sizeNote: "Home.co.th ระบุแฝด 45.5–47.9 ตร.ว.",
    caveat: "ข้อมูลเก่ากว่าระบุโครงการ 5.29–6.29 ลบ. ต้องเช็กแบบเดี่ยว/ที่เหลือ",
    sources: [
      { source: "Home.co.th", million: 4.59, note: "บ้านแฝด" },
      { source: "ข้อมูลเก่า", note: "โครงการ 5.29–6.29 ลบ." },
    ],
  },
];

export function seedRows() {
  return HUNT_SEEDS.map((s) => ({
    id: s.id,
    name: s.name,
    developer: s.developer,
    zone: s.zone,
    houseType: s.houseType,
    hasDetached: s.hasDetached,
    hasTwin: s.hasTwin,
    priceStartSatang: satangFromMillion(s.million),
    priceNote: s.priceNote,
    landNote: s.landNote,
    landWahTenths: s.landWahTenths,
    usableSqmMin: s.usableSqmMin,
    usableSqmMax: s.usableSqmMax,
    bedrooms: s.bedrooms,
    bathrooms: s.bathrooms,
    parking: s.parking,
    fitScore: s.fitScore,
    valueScore: s.valueScore,
    rank: s.rank,
    commuteNote: s.commuteNote,
    sizeNote: s.sizeNote,
    caveat: s.caveat,
  }));
}

export function seedPriceNotes() {
  return HUNT_SEEDS.flatMap((s) =>
    s.sources.map((src, i) => ({
      id: `${s.id}-src-${i}`,
      projectId: s.id,
      source: src.source,
      priceSatang: src.million != null ? satangFromMillion(src.million) : null,
      note: src.note,
      asOf: AS_OF,
    })),
  );
}
